package core.data.model;

import javafx.scene.paint.Color;

/**
 * <p> This is a Graphical implementation of player and the only thing it has in addition to normal Player is a field
 * for its color. </p> <p> Created by Majid Vaghari on 11/17/2015. </p>
 *
 * @author Majid Vaghari
 * @version 1.1.0 Updated constructor and added setters and getters for color field
 * @see Player
 * @since version 1.0.0
 */
public class GraphicalPlayer extends Player {
    /**
     * Represents color of this player.
     */
    private Color  color;
    /**
     * A unique ID generated by server.
     */
    private String id;

    /**
     * Constructor for making a new player default constructor is inaccessible because ID of this player cannot be
     * changed.
     *
     * @param name  name of the player
     * @param color color of the player
     * @param id    a unique ID generated by server
     */
    public GraphicalPlayer(String name, Color color, String id) {
        super(name);
        this.color = color;
        this.id = id;
    }

    /**
     * @return color of this player
     */
    public Color getColor() {
        return color;
    }

    /**
     * @param color the color of this player to set
     */
    public void setColor(Color color) {
        this.color = color;
    }

    /**
     * @return the unique ID of this player generated by server
     */
    public String getId() {
        return id;
    }
}
